#pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.Series([1,2,3, 'HASAN' ,0,np.nan,-1])

0        1
1        2
2        3
3    HASAN
4        0
5      NaN
6       -1
dtype: object

In [4]:
dates = pd.date_range('20260606',periods=6)
dates

DatetimeIndex(['2026-06-06', '2026-06-07', '2026-06-08', '2026-06-09',
               '2026-06-10', '2026-06-11'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6,4), index = dates , columns = ['a','b','c','d'])
df

                   a         b         c         d
2026-06-06 -1.170146  3.217698  0.151962 -0.051358
2026-06-07 -1.339624 -1.559562  1.502264  1.091203
2026-06-08  0.238137  0.013992 -0.171109  1.653059
2026-06-09 -1.505596 -0.054013 -1.498347 -1.313768
2026-06-10  1.440931  1.205840 -0.003605 -0.895238
2026-06-11 -0.142308  0.360574 -0.282814  2.638683

In [6]:
df.dtypes

a    float64
b    float64
c    float64
d    float64
dtype: object

In [7]:
df['a']

2026-06-06   -1.170146
2026-06-07   -1.339624
2026-06-08    0.238137
2026-06-09   -1.505596
2026-06-10    1.440931
2026-06-11   -0.142308
Freq: D, Name: a, dtype: float64

In [8]:
df.head(2)

                   a         b         c         d
2026-06-06 -1.170146  3.217698  0.151962 -0.051358
2026-06-07 -1.339624 -1.559562  1.502264  1.091203

In [9]:
df.tail(1)

                   a         b         c         d
2026-06-11 -0.142308  0.360574 -0.282814  2.638683

In [10]:
df.describe()

              a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean  -0.413101  0.530755 -0.050275  0.520430
std    1.145424  1.592657  0.961150  1.535641
min   -1.505596 -1.559562 -1.498347 -1.313768
25%   -1.297255 -0.037012 -0.254888 -0.684268
50%   -0.656227  0.187283 -0.087357  0.519922
75%    0.143026  0.994523  0.113070  1.512595
max    1.440931  3.217698  1.502264  2.638683

In [11]:
df.mean()

a   -0.413101
b    0.530755
c   -0.050275
d    0.520430
dtype: float64

In [12]:
df['b'].mean()

np.float64(0.5307547122176305)

In [13]:
df[ :3]

                   a         b         c         d
2026-06-06 -1.170146  3.217698  0.151962 -0.051358
2026-06-07 -1.339624 -1.559562  1.502264  1.091203
2026-06-08  0.238137  0.013992 -0.171109  1.653059

In [14]:
df.T

   2026-06-06  2026-06-07  2026-06-08  2026-06-09  2026-06-10  2026-06-11
a   -1.170146   -1.339624    0.238137   -1.505596    1.440931   -0.142308
b    3.217698   -1.559562    0.013992   -0.054013    1.205840    0.360574
c    0.151962    1.502264   -0.171109   -1.498347   -0.003605   -0.282814
d   -0.051358    1.091203    1.653059   -1.313768   -0.895238    2.638683

In [15]:
df.sort_values('b')

                   a         b         c         d
2026-06-07 -1.339624 -1.559562  1.502264  1.091203
2026-06-09 -1.505596 -0.054013 -1.498347 -1.313768
2026-06-08  0.238137  0.013992 -0.171109  1.653059
2026-06-11 -0.142308  0.360574 -0.282814  2.638683
2026-06-10  1.440931  1.205840 -0.003605 -0.895238
2026-06-06 -1.170146  3.217698  0.151962 -0.051358

In [16]:
df[df['a']>0]

                   a         b         c         d
2026-06-08  0.238137  0.013992 -0.171109  1.653059
2026-06-10  1.440931  1.205840 -0.003605 -0.895238

In [17]:
df[df['a']>1]

                   a        b         c         d
2026-06-10  1.440931  1.20584 -0.003605 -0.895238

In [18]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
b = a.reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
df = pd.DataFrame(b , index = dates , columns = ['ali', 'gholi' ,'reza', 'hasan'])
df

            ali  gholi  reza  hasan
2026-06-06    0      1     2      3
2026-06-07    4      5     6      7
2026-06-08    8      9    10     11
2026-06-09   12     13    14     15
2026-06-10   16     17    18     19
2026-06-11   20     21    22     23